import Link from "next/link"

export default function About() {
    return (
        <section>
            <h1>A little bit about me...</h1>
            <p>The very first time I took a coding class, I hated it! I was frustrated by the precise exactitudes of coding languages, and ignorant of the plethora of learning resources available. Instead I just focused on studying the humanities, which was my major at the time. After graduating from Brigham Young University in 2012, I moved on to a master's program in art history at the University of Utah. After writing a thesis on a Japanese drum, focusing on the intersection of traditional arts, international commerce and modern warfare, I began my search for work in museums and art galleries. My search was unfruitful.</p>
            <p>Unsure of what to do for a career, I learned about coding boot camps and the abundance of job opportunities in tech. I had developed a solid work ethic in grad school, so I picked up some books on HTML, CSS, and JavaScript, and started by coding out copies of websites I found online. I was instantly hooked! Shortly after discovering the fun and challenge of writing code, I took my first coding course at Salt Lake Community College, which I completed in 2016. A few months after that, I got my first coding job at <a target="blank" href="https://www.hydroblaster.com/">Hydro Engineering</a> in South Salt Lake.</p>
            <p>As a dedicated web developer in the marketing team, I was free to focus entirely on improving the website. I learned SEO best practices, the importance of consistent visual branding, and parsing JSON data. I also did some backend work using PHP and MySQL (and a little bit of Python too). I didn't get a lot of tickets coming down from the top, so I had to find ways to keep myself busy. I implemented the Bootstrap library to establish a flawless layout on both desktop and mobile, built a product comparison app using local storage, and spearheaded a major branding update that is still in use today.</p>
            <p>After 18 months, my desire to increase my coding skills grew, and I enrolled in another coding bootcamp through the University of Utah. Having already established a solid foundation on HTML, CSS, and JavaScript, I learned React, Node.js, and database integration. I also finally learned how to use GitHub! A team of fellow students and I developed a complete MERN stack app for our final project. Feeling confident in my newfound skills, I started looking for a new role that offered more challenges and opportunities.</p>
            <p>In summer of 2019, I started at <a target="blank" href="https://www.ivanti.com/">Ivanti</a> as a frontend developer. It was my first time working on a full dev team, which exponentially accelerated my career growth. The team changed over the years, but I was able to learn something from each of them. As part of the marketing department, we frequently collaborated with creative designers, project managers, content editors, and executive leadership. With a website as large as Ivanti's, and with as many people contributing to it, we had tickets coming in all the time, from minor stylistic adjustments to major overhauls.</p>
            <p>One of my first big projects was overseeing the site's rebranding, creating flexible and reusable XML templates with accompanying SCSS. I was responsible for code cleanup, visual consistency, and architectural improvements. Ivanti would see several additional branding updates during my time there, all of which I took ownership of. Because Ivanti is an international company with a wide-ranging customer base, optimizing the UX/UI and debugging applications for multiple operating systems, browsers, devices, and languages.</p>
            <p>After a few years, my responsibilities expanded. I was promoted to senior developer, had a new frontend developer to mentor, and had more opportunities to create meaningful improvements to the site. I gained an eye for detail, pattern recognition, and creative solutions to complex problems. I decreased reliance on third party libraries, reduced load times, and shipped measurable performance improvements, which in turn led to decreased bounce rates, greater customer conversion, and increased sales.</p>
            <p>My very first exposure to Vue.js and AI coding tools came when I was tasked with creating an icon library for internal use. But after a few tutorials and experimentation, I delivered a complete app that utilized API calls, keyword searches, file manipulation (attributes like size, color, file-type), and downloading multiple resources simultaneously. I was able to fast-track the development process by using GitHub Copilot, which I directed with precise and clear prompts. My newly developed app enabled users to easily maintain visual branding in important customer-facing presentations.</p>
            <p>In January of 2026, I was unfortunately caught up in a departmental restructuring that ended my time at Ivanti. But after taking time to learn new skills I'm developing every day, I'm ready to re-enter the workforce as a frontend or even fullstack developer in marketing or software engineering!</p>
            <h2>So what's next?</h2>
            <p>I'm accepting any and all challenges! </p>
            <p>Send me an <Link href="contact">email</Link> or contact me on <a href="https://www.linkedin.com/in/seth-baldridge-591282175/">LinkedIn</a>, and let's talk about what I can do for your team!</p>
        </section>
    )
}